services:
  mongodb:
    image: "mongo"
    # container_name: mongodb
    volumes:
      - datadb:/data/db
    # environment:
    #   - MONGO_INITDB_ROOT_USERNAME=max
    #   - MONGO_INITDB_ROOT_PASSWORD=secret
    env_file:
      - ./env/mongo.env

  backend:
    build: ./backend
    # build:
    #   context: ./backend
    #   dockerfile: Dockerfile
    image: "goals-node"
    env_file:
      - ./env/backend.env
    volumes:
      - logs:/app/logs
      - ./backend:/app
      - /app/node_modules
    ports:
      - "80:80"
    depends_on:
      - mongodb

  frontend:
    build: ./frontend
    image: "goals-react"
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src
    stdin_open: true
    tty: true
    depends_on:
      - backend

volumes:
  datadb:
  logs:
